### ISSUE TITLE
PageBounds 好像对foreach的支持太好

### ISSUE THREAD

**Issue by wentaotang** [miemiedev/mybatis-paginator#1]
《!--这样写 好像PageBounds没有起任何作用--> 
<select id="findHistoryByRoomIds" parameterType="java.util.Map" resultType="WebConference">
        select startTime,subject,ofuserext.nickname as owner, endTime,huijianroomid as huiJianRoomId 
        from webConference,ofuserext
        where  isdeleted=0
        and huijianroomid in 
        <foreach collection="maps" item="id" open="(" separator="," close=")">
            #{id,jdbcType=INTEGER}
        </foreach> 
        and endTime <![CDATA[ < ]]> NOW() and ofuserext.username=webConference.owner order by endTime desc
    </select>

但是，我这么写就没有问题了，PageBounds正常：
<select id="findHistoryByRoomIds" parameterType="java.util.Map" resultType="WebConference">
        select startTime,subject,ofuserext.nickname as owner, endTime,huijianroomid as huiJianRoomId 
        from webConference,ofuserext
        where  isdeleted=0
        and huijianroomid in (1,2)
        and endTime <![CDATA[ < ]]> NOW() and ofuserext.username=webConference.owner order by endTime desc
    </select>
上面foreach的实际结果值就是(1,2)

**Comment by gitwudi** [comment]
版本1.2.17  传入的实体对象中，包含list，分页查询会失败，但如果封装到map里面是OK的，已重现。。
