### ISSUE TITLE
count 执行sql和原分页sql不在同一事务中

### ISSUE THREAD

**Issue by clarkhan** [miemiedev/mybatis-paginator#2]
使用SqlHelp.getCount(……)查询记录总数使用的是单独的connection，与原查询的sql不在同一个事务中。

**Comment by kingdh** [comment]
你好,我用压力测试工具测试, 10个线程循环查询一个分页接口, 会产生死锁. 最后总查询量在5000以内就会发生.

**Comment by kingdh** [comment]
用的是1.2.15版

**Comment by hyperknob** [comment]
请问这个问题解决了么？我也遇到了同样的问题
