### ISSUE TITLE
获取总记录数出问题

### ISSUE THREAD

**Issue by wentaotang** [miemiedev/mybatis-paginator#6]
使用版本：1.2.15
我使用mybatis-paginator，定义一个list()方法完成数据查询的功能，第一次查询的结果和总记录数都没有问题，当我界面中删除其中一条记录的时候，然后再次执行list()方法刷新数据的时候，把数据集合转换成PageList的时候，通过pageList.getPaginator().getTotalCount() 的总记录数还是未删除前的总记录数，相当于删除一条记录，pageList.getPaginator().getTotalCount() 的值总是第一次请求时候的值，一直没有改变？ 无论是我执行删除还是增加操作都无法改变总记录数，仅搜索结果的总记录数是ok，而这些方法执行的都是同样的代码。

**Comment by miemiedev** [comment]
请更新至1.2.16
